apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
